codecov:
  require_ci_to_pass: true

flags:
  unit:
    paths:
      - heiplanet_data/
    carryforward: false
  integration:
    paths:
      - heiplanet_data/
    carryforward: true

coverage:
  status:
    project:
      default:
        target: 80
    patch:
      default:
        target: 80